services:
  web:
    build: .
    ports:
      - "9092:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html
      - ./cgi-bin:/usr/share/nginx/cgi-bin
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - TZ=Europe/Helsinki